name: Deploy Extension
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn; cd ./media-src; yarn #; cd ..;yarn global add vsce; vsce package
      - name: Test
        run: npm test
      - name: Upload VSIX as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: vsix-package
          path: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          packagePath: ''
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        id: publishToOpenVSX
        with:
          pat: 1312321321231 #${{ secrets.OPEN_VSX_TOKEN }}
      
